version: "3.4"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    user: ${USERID}:${GROUPID}
    ports:
      - 8000:8000
      - 8081:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/docker/portainer:/data
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=Asia/Kolkata
      - WEBUI_PORT=82
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8082:8080
    volumes:
      - /home/pi/docker/qbittorrent:/config
      - /home/pi/docker/downloads:/downloads
  filelist:
    image: bin20088/h5ai:latest
    container_name: h5ai
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=Asia/Kolkata
    ports:
      - 8083:80
    volumes:
      - /home/pi/docker/downloads:/h5ai
      - /home/pi/docker/h5ai:/config
  filemanagement:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
    ports:
      - 8084:80
    volumes:
      - /home/pi/docker/downloads:/srv
      - /home/pi/docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /home/pi/docker/filebrowser/settings.json:/config/settings.json
  gerberaserver:
    image: gerbera/gerbera:edge
    container_name: gerbera-dlna
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /home/pi/docker/downloads:/content:ro
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    user: ${USERID}:${GROUPID}
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
